[package]
name = "ucelofka"
version = "0.1.0"
authors = ["Stepan Henek"]
edition = "2018"

[dependencies]
tera = "1.0.0-beta.11"
clap = "2.33"
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
serde_json = "1.0"
