[package]
name = "ucelofka"
version = "0.2.0"
authors = ["Stepan Henek"]
edition = "2018"
description = "Simple program to issue invoices"
license = "GPL-3.0"
readme = "README.md"
keywords = ["cli", "invoice", "git"]
repository = "https://github.com/shenek/ucelofka"
categories = ["command-line-utilities"]

include = ["default", "src"]

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "2.33"
fluent = "0.9.1"
fluent-bundle = "0.9.1"
fluent-langneg = "0.11.1"
git2 = "0.11.0"
lazy_static = "1.4.0"
include_dir = { version = "0.5.0" }
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
serde_json = "1.0"
tera = "1.0.1"
unic-langid = { version = "0.7.1", features = ["macros"]}

[dev-dependencies]
assert_cmd = "0.12"
tempfile = "3.1"
test-case = "1.0.0"

[[bin]]
name = "ucelofka"
path = "src/main.rs"
