[package]
name = "ucelofka"
version = "0.1.0"
authors = ["Stepan Henek"]
edition = "2018"
description = "Simple program to issue invoices"
license = "GPLv3"
readme = "README.md"
keywords = ["cli", "invoice", "git"]
repository = "https://github.com/shenek/ucelovka"
categories = ["command-line-utilities"]

build = "build.rs"
include = ["default"]

[dependencies]
chrono = "0.4"
clap = "2.33"
failure = "0.1"
includedir = { version = "0.5", features = ["flate2"] }
phf = "0.7.21"
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
serde_json = "1.0"
tera = "1.0.1"

[build-dependencies]
includedir_codegen = "0.4"

[[bin]]
name = "ucelofka"
path = "src/main.rs"
